# Generated by Django 2.0.7 on 2018-08-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20180809_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(default='16ebe6ee-5c31-4cab-9f74-e5dad9400316', editable=False, max_length=200, primary_key=True, serialize=False),
        ),
    ]
